name: ci

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: test

    steps:
      - uses: actions/checkout@v2

      - run: echo 'All tests passed'

  deploy:
    runs-on: ubuntu-latest

    needs: [test]

    env:
      NODE_ENV: production
      IMAGE_NAME: app

    steps:
      - uses: actions/checkout@v2

      - run: echo "IMAGE=gcr.io/${{ secrets.PROJECT_ID }}/${{ env.IMAGE_NAME }}:$GITHUB_SHA" >> $GITHUB_ENV

      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.PROJECT_ID }}
          export_default_credentials: true

      - uses: hashicorp/setup-terraform@v1

      - run: gcloud --quiet auth configure-docker

      - run: docker build --tag ${{ env.IMAGE }} .

      - run: docker push ${{ env.IMAGE }}

      - run: terraform init
        working-directory: ./infra

      - run: terraform plan \
          -var image=${{ env.IMAGE }} \
          -var project=${{ secrets.PROJECT_ID }}
        working-directory: ./infra

      # - run: terraform apply -var="image=${{ env.image_tag }}" --auto-approve
      #   working-directory: ./infra
